[platformio]
src_dir = firmware/aviation_firmware/src
include_dir = firmware/aviation_firmware/include

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++11
